"""Initial migration

Revision ID: 2a5cdb0a3008
Revises: 
Create Date: 2025-12-03 22:05:35.522742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5cdb0a3008'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_learned_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('weight_modifier', sa.Float(), nullable=True),
    sa.Column('feedback_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sos_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('alert_email', sa.String(length=255), nullable=True),
    sa.Column('alert_phone', sa.String(length=50), nullable=True),
    sa.Column('agent_token', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_agent_token'), ['agent_token'], unique=True)

    op.create_table('alert_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('sms_to', sa.String(length=50), nullable=True),
    sa.Column('min_severity', sa.String(length=20), nullable=True),
    sa.Column('always_on', sa.Boolean(), nullable=True),
    sa.Column('off_start_hour', sa.Integer(), nullable=True),
    sa.Column('off_end_hour', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_alert_pref_organization'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_preference_organization_id'), ['organization_id'], unique=False)

    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_device_organization'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_mac'), ['mac'], unique=True)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('mitre_tag', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_behavior_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('behavior', sa.String(length=256), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_file_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('rule_name', sa.String(length=120), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_network_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dest_ip', sa.String(length=64), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_process_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=256), nullable=True),
    sa.Column('command_line', sa.String(length=1024), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_risk_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('highest_severity', sa.String(length=20), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='fk_ai_signal_device'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_ai_signal_organization'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_signal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_signal_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_signal_mac'), ['mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_signal_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_signal_ts'), ['ts'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_email', sa.Boolean(), nullable=True),
    sa.Column('sent_sms', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('adjusted_score', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_alert_organization'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='fk_telemetry_device'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_telemetry_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_telemetry_ts'), ['ts'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=True),
    sa.Column('mac', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.Integer(), nullable=True),
    sa.Column('correlation_key', sa.String(length=255), nullable=True),
    sa.Column('correlation_score', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    with op.batch_alter_table('device_telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_telemetry_ts'))
        batch_op.drop_index(batch_op.f('ix_device_telemetry_device_id'))

    op.drop_table('device_telemetry')
    op.drop_table('alert')
    with op.batch_alter_table('ai_signal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_signal_ts'))
        batch_op.drop_index(batch_op.f('ix_ai_signal_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_signal_mac'))
        batch_op.drop_index(batch_op.f('ix_ai_signal_device_id'))

    op.drop_table('ai_signal')
    op.drop_table('ai_risk_score')
    op.drop_table('ai_process_event')
    op.drop_table('ai_network_event')
    op.drop_table('ai_file_scan')
    op.drop_table('ai_event')
    op.drop_table('ai_behavior_event')
    op.drop_table('user')
    op.drop_table('incident')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_mac'))
        batch_op.drop_index(batch_op.f('ix_device_last_seen'))

    op.drop_table('device')
    with op.batch_alter_table('alert_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_preference_organization_id'))

    op.drop_table('alert_preference')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_agent_token'))

    op.drop_table('organization')
    op.drop_table('subscription')
    op.drop_table('ai_learned_rule')
    # ### end Alembic commands ###
